"""todo table

Revision ID: 727fe2fdbd93
Revises: 7fece16d9da4
Create Date: 2018-12-06 19:22:33.236261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727fe2fdbd93'
down_revision = '7fece16d9da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
